title: <p align="center"> Rohit Chaudhary </p>
logo: /assets/img/Final_DP.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/rohit-chaudhary-491875a5//">LinkedIn</a> |
  <a href="https://github.com/Rohitnith">GitHub</a>
 <br>   
 I'm a AI & ML enthusiast.
 Exploring  field of AI & ML and looking 
 forward to implement it for solving the 
 business challenges.
 Please do contact me to collaborate on any open project.
  <br>
  </p>
  
  
  
  
  
  
  
 
  
  
theme: jekyll-theme-minimal
